"""removed is_platinum

Revision ID: aa9499dde8f8
Revises: cc6e67feb28f
Create Date: 2024-08-07 11:18:44.336944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9499dde8f8'
down_revision = 'cc6e67feb28f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album_table', schema=None) as batch_op:
        batch_op.drop_column('is_platinum')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_platinum', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
