"""add platinum

Revision ID: cc6e67feb28f
Revises: 687b0ecc40dd
Create Date: 2024-08-07 11:14:51.488961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6e67feb28f'
down_revision = '687b0ecc40dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_platinum', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album_table', schema=None) as batch_op:
        batch_op.drop_column('is_platinum')

    # ### end Alembic commands ###
